# Generated by Django 5.2 on 2026-01-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0014_booktag_book_is_archived_alter_book_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='年级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='班级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('students', models.ManyToManyField(blank=True, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作业说明')),
                ('due_date', models.DateTimeField(verbose_name='截止时间')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('books', models.ManyToManyField(blank=True, related_name='assignments', to='books.book', verbose_name='关联教材')),
                ('chapters', models.ManyToManyField(blank=True, related_name='assignments', to='books.chapter', verbose_name='关联章节')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
                ('classes', models.ManyToManyField(related_name='assignments', to='teacher.class', verbose_name='分配班级')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('type', models.CharField(choices=[('assignment', '作业通知'), ('reminder', '提醒通知'), ('feedback', '反馈通知'), ('system', '系统通知')], default='system', max_length=20, verbose_name='通知类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='年级')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='入学日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属院系')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='办公室')),
                ('office_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='办公时间')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师档案',
                'verbose_name_plural': '教师档案',
            },
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='资源描述')),
                ('file', models.FileField(upload_to='teaching_resources/', verbose_name='资源文件')),
                ('resource_type', models.CharField(choices=[('ppt', 'PPT'), ('video', '视频'), ('document', '文档'), ('other', '其他')], default='other', max_length=20, verbose_name='资源类型')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_resources', to=settings.AUTH_USER_MODEL, verbose_name='上传教师')),
            ],
            options={
                'verbose_name': '教学资源',
                'verbose_name_plural': '教学资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='教师反馈')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否迟交')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.assignment', verbose_name='作业')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='批改教师')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
