# Generated by Django 4.2.7 on 2026-01-11 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_remove_book_introduction'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.AutoField(db_column='resource_id', primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('resource_type', models.CharField(help_text='文档、视频、音频、图片等', max_length=50, verbose_name='资源类型')),
                ('resource_url', models.CharField(max_length=255, verbose_name='资源存储地址')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('resource_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='资源描述')),
            ],
            options={
                'verbose_name': '班级资源',
                'verbose_name_plural': '班级资源',
                'db_table': 'class_resource',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseDesign',
            fields=[
                ('id', models.AutoField(db_column='design_id', primary_key=True, serialize=False)),
                ('design_title', models.CharField(max_length=200, verbose_name='设计标题')),
                ('design_content', models.TextField(blank=True, null=True, verbose_name='设计内容')),
                ('teaching_hours', models.IntegerField(blank=True, null=True, verbose_name='预计课时')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程设计',
                'verbose_name_plural': '课程设计',
                'db_table': 'course_design',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(db_column='homework_id', primary_key=True, serialize=False)),
                ('homework_name', models.CharField(max_length=200, verbose_name='作业名称')),
                ('homework_content', models.TextField(verbose_name='作业内容')),
                ('start_time', models.DateTimeField(verbose_name='作业发布时间')),
                ('end_time', models.DateTimeField(verbose_name='作业截止时间')),
                ('total_score', models.IntegerField(default=100, verbose_name='作业总分')),
                ('status', models.IntegerField(default=1, help_text='1-未发布，2-已发布，3-已截止', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'homework',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(db_column='notice_id', primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('notice_content', models.TextField(verbose_name='通知内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('read_count', models.IntegerField(default=0, verbose_name='已读次数')),
                ('status', models.IntegerField(default=1, help_text='1-有效，0-已删除', verbose_name='状态')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notice',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='student_id', primary_key=True, serialize=False)),
                ('student_no', models.CharField(db_column='student_number', max_length=50, unique=True, verbose_name='学生学号')),
                ('student_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('gender', models.IntegerField(blank=True, help_text='1-男，2-女，0-未知', null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('status', models.IntegerField(default=1, help_text='1-正常，0-离校/退班', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.AutoField(db_column='submit_id', primary_key=True, serialize=False)),
                ('submit_content', models.TextField(blank=True, null=True, verbose_name='提交内容')),
                ('submit_file_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='提交文件地址')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('correct_time', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('correct_comment', models.TextField(blank=True, null=True, verbose_name='批改评语')),
                ('status', models.IntegerField(default=1, help_text='1-未提交，2-已提交，3-已批改，4-已退回', verbose_name='状态')),
            ],
            options={
                'verbose_name': '学生作业提交',
                'verbose_name_plural': '学生作业提交',
                'db_table': 'student_homework',
            },
        ),
        migrations.CreateModel(
            name='StudentLearningProgress',
            fields=[
                ('id', models.AutoField(db_column='progress_id', primary_key=True, serialize=False)),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长（分钟）')),
                ('learn_status', models.IntegerField(default=1, help_text='1-未学习，2-学习中，3-已完成', verbose_name='学习状态')),
                ('last_learn_time', models.DateTimeField(blank=True, null=True, verbose_name='最后学习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生学习进度',
                'verbose_name_plural': '学生学习进度',
                'db_table': 'student_learning_progress',
            },
        ),
        migrations.CreateModel(
            name='StudentNoticeRead',
            fields=[
                ('id', models.AutoField(db_column='read_id', primary_key=True, serialize=False)),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('is_read', models.IntegerField(default=0, help_text='0-未读，1-已读', verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '学生通知阅读记录',
                'verbose_name_plural': '学生通知阅读记录',
                'db_table': 'student_notice_read',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(db_column='teacher_id', primary_key=True, serialize=False)),
                ('teacher_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='教师编号')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='教师姓名')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属部门')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='教师简介')),
                ('status', models.IntegerField(default=1, help_text='1-正常，0-禁用', verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSetting',
            fields=[
                ('id', models.AutoField(db_column='setting_id', primary_key=True, serialize=False)),
                ('setting_key', models.CharField(help_text='theme、notify_type等', max_length=50, verbose_name='设置项key')),
                ('setting_value', models.CharField(max_length=255, verbose_name='设置项值')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师个人设置',
                'verbose_name_plural': '教师个人设置',
                'db_table': 'teacher_setting',
            },
        ),
        migrations.CreateModel(
            name='TeachingToolLog',
            fields=[
                ('id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text='计时器、随机点名、答题卡等', max_length=100, verbose_name='工具名称')),
                ('use_time', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('use_duration', models.IntegerField(default=0, verbose_name='使用时长（秒）')),
            ],
            options={
                'verbose_name': '教学工具使用记录',
                'verbose_name_plural': '教学工具使用记录',
                'db_table': 'teaching_tool_log',
                'ordering': ['-use_time'],
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='books',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='teachingresource',
            options={'ordering': ['-upload_time'], 'verbose_name': '教学资源', 'verbose_name_plural': '教学资源'},
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='class',
            name='book',
            field=models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='books.book', verbose_name='关联教材'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.CharField(default='1', max_length=10, verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.IntegerField(default=1, help_text='1-正常，0-解散', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='chapter',
            field=models.ForeignKey(blank=True, db_column='chapter_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_resources', to='books.chapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='resource_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='资源描述'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='resource_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='资源名称'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='resource_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='资源存储地址'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, db_column='class_desc', null=True, verbose_name='班级描述'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(blank=True, default='2024', max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(db_column='class_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.CharField(default='计算机科学', max_length=100, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(db_column='class_name', max_length=100, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='id',
            field=models.AutoField(db_column='resource_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='resource_type',
            field=models.CharField(blank=True, help_text='课件、教案、习题等', max_length=50, null=True, verbose_name='资源类型'),
        ),
        migrations.AddIndex(
            model_name='teachingresource',
            index=models.Index(fields=['chapter'], name='teaching_re_chapter_2ecbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingresource',
            index=models.Index(fields=['teacher'], name='teaching_re_teacher_971adc_idx'),
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='teachingresource',
            table='teaching_resource',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='teachingtoollog',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='teacher.class', verbose_name='使用的班级'),
        ),
        migrations.AddField(
            model_name='teachingtoollog',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='teacher.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='teachersetting',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='teacher.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='studentnoticeread',
            name='notice',
            field=models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='teacher.notice', verbose_name='通知'),
        ),
        migrations.AddField(
            model_name='studentnoticeread',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='teacher.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='chapter',
            field=models.ForeignKey(db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='books.chapter', verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='teacher.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='teacher.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='correct_teacher',
            field=models.ForeignKey(blank=True, db_column='correct_teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_homeworks', to='teacher.teacher', verbose_name='批改教师'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='homework',
            field=models.ForeignKey(db_column='homework_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.homework', verbose_name='作业'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='teacher.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='notice',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_id', help_text='NULL表示全体学生', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='notice',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to='teacher.teacher', verbose_name='发布教师'),
        ),
        migrations.AddField(
            model_name='homework',
            name='chapter',
            field=models.ForeignKey(db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='books.chapter', verbose_name='关联章节'),
        ),
        migrations.AddField(
            model_name='homework',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='teacher.teacher', verbose_name='创建教师'),
        ),
        migrations.AddField(
            model_name='coursedesign',
            name='chapter',
            field=models.ForeignKey(db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_designs', to='books.chapter', verbose_name='关联章节'),
        ),
        migrations.AddField(
            model_name='coursedesign',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_designs', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='coursedesign',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_designs', to='teacher.teacher', verbose_name='设计教师'),
        ),
        migrations.AddField(
            model_name='classresource',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='classresource',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_resources', to='teacher.teacher', verbose_name='所属教师'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to='teacher.teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_resources', to='teacher.teacher', verbose_name='上传教师'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'book')},
        ),
        migrations.AddIndex(
            model_name='teachingtoollog',
            index=models.Index(fields=['teacher'], name='teaching_to_teacher_606ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingtoollog',
            index=models.Index(fields=['tool_name'], name='teaching_to_tool_na_d30acb_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingtoollog',
            index=models.Index(fields=['class_obj'], name='teaching_to_class_i_e460f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersetting',
            unique_together={('teacher', 'setting_key')},
        ),
        migrations.AddIndex(
            model_name='studentnoticeread',
            index=models.Index(fields=['student'], name='student_not_student_d23890_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnoticeread',
            unique_together={('notice', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentlearningprogress',
            index=models.Index(fields=['teacher'], name='student_lea_teacher_a5cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlearningprogress',
            index=models.Index(fields=['learn_status'], name='student_lea_learn_s_f4e06f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlearningprogress',
            unique_together={('student', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='studenthomework',
            index=models.Index(fields=['student'], name='student_hom_student_626f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studenthomework',
            index=models.Index(fields=['status'], name='student_hom_status_3d4992_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studenthomework',
            unique_together={('homework', 'student')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_obj'], name='student_class_i_c7140f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_name'], name='student_student_27a9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['teacher'], name='notice_teacher_77ad22_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['class_obj'], name='notice_class_i_b417bd_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['teacher'], name='homework_teacher_19486a_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_obj'], name='homework_class_i_f0090e_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['status'], name='homework_status_68b5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedesign',
            index=models.Index(fields=['class_obj'], name='course_desi_class_i_916d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedesign',
            index=models.Index(fields=['chapter'], name='course_desi_chapter_be7d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='classresource',
            index=models.Index(fields=['class_obj'], name='class_resou_class_i_d71a23_idx'),
        ),
        migrations.AddIndex(
            model_name='classresource',
            index=models.Index(fields=['teacher'], name='class_resou_teacher_5bf51c_idx'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
