# Generated by Django 4.2.7 on 2026-01-13 01:50

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations.operations import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_subtitle_bookversion_subtitle'),
        ('teacher', '0003_add_user_to_student'),
    ]

    operations = [
        # 先删除所有可能冲突的表（如果存在）
        migrations.RunSQL(
            "DROP TABLE IF EXISTS report;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS student_class;",
            reverse_sql=""
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('student', '学生个人报告'), ('class', '班级整体报告'), ('comparison', '对比分析报告')], max_length=20, verbose_name='报告类型')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('include_progress', models.BooleanField(default=True, verbose_name='包含学习进度')),
                ('include_homework', models.BooleanField(default=True, verbose_name='包含作业完成情况')),
                ('include_attendance', models.BooleanField(default=False, verbose_name='包含出勤统计')),
                ('include_performance', models.BooleanField(default=True, verbose_name='包含成绩分析')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], default='pdf', max_length=10, verbose_name='导出格式')),
                ('report_data', models.JSONField(blank=True, null=True, verbose_name='报告数据')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='报告文件路径')),
                ('status', models.IntegerField(default=1, help_text='1-生成中，2-已完成，3-生成失败', verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 'report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(db_column='student_class_id', primary_key=True, serialize=False)),
                ('student', models.IntegerField(db_column='student_id', verbose_name='学生ID')),
                ('class_obj', models.IntegerField(db_column='class_id', verbose_name='班级ID')),
                ('is_active', models.BooleanField(default=True, help_text='True-在班，False-已退班', verbose_name='是否有效')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='join_time', verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, db_column='leave_time', null=True, verbose_name='离开时间')),
            ],
            options={
                'verbose_name': '学生班级关系',
                'verbose_name_plural': '学生班级关系',
                'db_table': 'student_class',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studenthomework',
            options={'managed': False, 'verbose_name': '学生作业提交', 'verbose_name_plural': '学生作业提交'},
        ),
        migrations.AlterModelOptions(
            name='teachingresource',
            options={'ordering': ['-created_at'], 'verbose_name': '教学资源', 'verbose_name_plural': '教学资源'},
        ),

        # 使用SeparateDatabaseAndState来处理可能冲突的列添加
        SeparateDatabaseAndState(
            database_operations=[
                # 数据库层面不执行任何操作，避免冲突
            ],
            state_operations=[
                # 状态层面添加所有字段，保持Django模型状态同步
                migrations.AddField(
                    model_name='class',
                    name='course_code',
                    field=models.CharField(blank=True, help_text='用于学生加入班级的唯一码', max_length=20, null=True, unique=True, verbose_name='课程码'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='file_hash',
                    field=models.CharField(blank=True, db_column='file_hash', help_text='MD5或SHA256哈希值', max_length=64, null=True, verbose_name='文件哈希值'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='file_size',
                    field=models.BigIntegerField(db_column='file_size', default=0, verbose_name='文件大小（字节）'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='mime_type',
                    field=models.CharField(blank=True, db_column='mime_type', max_length=100, null=True, verbose_name='文件MIME类型'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='retry_count',
                    field=models.IntegerField(db_column='retry_count', default=0, verbose_name='重试次数'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='storage_path',
                    field=models.TextField(blank=True, db_column='storage_path', null=True, verbose_name='完整存储路径'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='upload_ip',
                    field=models.GenericIPAddressField(blank=True, db_column='upload_ip', null=True, verbose_name='上传IP地址'),
                ),
                migrations.AddField(
                    model_name='classresource',
                    name='upload_status',
                    field=models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], db_column='upload_status', default='completed', max_length=20, verbose_name='上传状态'),
                ),
                migrations.AddField(
                    model_name='notice',
                    name='is_important',
                    field=models.BooleanField(default=False, verbose_name='是否重要'),
                ),
                migrations.AddField(
                    model_name='notice',
                    name='type',
                    field=models.CharField(choices=[('system', '系统通知'), ('assignment', '作业提醒'), ('student', '学生消息'), ('announcement', '公告')], default='announcement', max_length=20, verbose_name='通知类型'),
                ),
                migrations.AddField(
                    model_name='student',
                    name='class_name',
                    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属班级'),
                ),
                migrations.AddField(
                    model_name='studentlearningprogress',
                    name='book',
                    field=models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='books.book', verbose_name='教材'),
                ),
                migrations.AddField(
                    model_name='studentlearningprogress',
                    name='is_completed',
                    field=models.BooleanField(default=False, verbose_name='是否已完成'),
                ),
                migrations.AddField(
                    model_name='studentlearningprogress',
                    name='progress',
                    field=models.FloatField(default=0, verbose_name='学习进度'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='category',
                    field=models.CharField(blank=True, db_column='category', max_length=100, null=True, verbose_name='资源分类'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='创建时间'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='description',
                    field=models.TextField(blank=True, db_column='description', null=True, verbose_name='资源描述'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='file',
                    field=models.TextField(db_column='file', default='', help_text='完整文件路径或文件名', verbose_name='文件存储路径'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='file_hash',
                    field=models.CharField(blank=True, db_column='file_hash', help_text='MD5或SHA256哈希值', max_length=64, null=True, verbose_name='文件哈希值'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='file_size',
                    field=models.BigIntegerField(blank=True, db_column='file_size', null=True, verbose_name='文件大小（字节）'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='is_public',
                    field=models.BooleanField(db_column='is_public', default=True, verbose_name='是否公开'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='mime_type',
                    field=models.CharField(blank=True, db_column='mime_type', max_length=100, null=True, verbose_name='文件MIME类型'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='retry_count',
                    field=models.IntegerField(db_column='retry_count', default=0, verbose_name='重试次数'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='storage_path',
                    field=models.TextField(blank=True, db_column='storage_path', null=True, verbose_name='完整存储路径'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='title',
                    field=models.CharField(db_column='title', default='未命名资源', max_length=200, verbose_name='资源标题'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, db_column='updated_at', null=True, verbose_name='更新时间'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='upload_ip',
                    field=models.GenericIPAddressField(blank=True, db_column='upload_ip', null=True, verbose_name='上传IP地址'),
                ),
                migrations.AddField(
                    model_name='teachingresource',
                    name='upload_status',
                    field=models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], db_column='upload_status', default='completed', max_length=20, verbose_name='上传状态'),
                ),
            ]
        ),
        # 使用SeparateDatabaseAndState来处理可能冲突的字段修改
        SeparateDatabaseAndState(
            database_operations=[
                # 数据库层面不执行任何操作，避免冲突
            ],
            state_operations=[
                # 状态层面修改所有字段，保持Django模型状态同步
                migrations.AlterField(
                    model_name='studentlearningprogress',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='teachingresource',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='teachingresource',
                    name='resource_type',
                    field=models.CharField(db_column='resource_type', default='file', max_length=20, verbose_name='资源类型'),
                ),
            ]
        ),
        # 使用SeparateDatabaseAndState来处理所有索引添加和表修改
        SeparateDatabaseAndState(
            database_operations=[
                # 数据库层面不执行任何操作，避免冲突
            ],
            state_operations=[
                # 状态层面添加所有索引，保持Django模型状态同步
                migrations.AddIndex(
                    model_name='classresource',
                    index=models.Index(fields=['file_hash'], name='class_resou_file_ha_2671fd_idx'),
                ),
                migrations.AddIndex(
                    model_name='classresource',
                    index=models.Index(fields=['upload_status'], name='class_resou_upload__18774b_idx'),
                ),
                migrations.AddIndex(
                    model_name='studentlearningprogress',
                    index=models.Index(fields=['student'], name='student_lea_student_01345e_idx'),
                ),
                migrations.AddIndex(
                    model_name='studentlearningprogress',
                    index=models.Index(fields=['chapter'], name='student_lea_chapter_c36c49_idx'),
                ),
                migrations.AddIndex(
                    model_name='teachingresource',
                    index=models.Index(fields=['file_hash'], name='teacher_tea_file_ha_6531ff_idx'),
                ),
                migrations.AddIndex(
                    model_name='teachingresource',
                    index=models.Index(fields=['upload_status'], name='teacher_tea_upload__58d5a1_idx'),
                ),
                migrations.AlterModelTable(
                    name='teachingresource',
                    table='teacher_teachingresource',
                ),
            ]
        ),
        # 使用SeparateDatabaseAndState来处理剩余的字段添加和索引
        SeparateDatabaseAndState(
            database_operations=[
                # 数据库层面不执行任何操作，避免冲突
            ],
            state_operations=[
                # 状态层面添加所有字段和索引，保持Django模型状态同步
                migrations.AddField(
                    model_name='report',
                    name='class_obj',
                    field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.class', verbose_name='所属班级'),
                ),
                migrations.AddField(
                    model_name='report',
                    name='student',
                    field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.student', verbose_name='学生'),
                ),
                migrations.AddField(
                    model_name='report',
                    name='teacher',
                    field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.teacher', verbose_name='生成教师'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['teacher'], name='report_teacher_43b12b_idx'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['class_obj'], name='report_class_i_e65080_idx'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['student'], name='report_student_f6df50_idx'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['report_type'], name='report_report__a84470_idx'),
                ),
                migrations.AddIndex(
                    model_name='report',
                    index=models.Index(fields=['status'], name='report_status_74972f_idx'),
                ),
            ]
        ),
    ]