# Generated by Django 6.0.4 on 2026-04-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_report_studentclass_remove_teachingtoollog_class_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件存储路径')),
                ('storage_path', models.TextField(blank=True, db_column='storage_path', null=True, verbose_name='完整存储路径')),
                ('file_size', models.BigIntegerField(db_column='file_size', verbose_name='文件大小（字节）')),
                ('file_hash', models.CharField(blank=True, db_column='file_hash', max_length=64, null=True, verbose_name='文件哈希值')),
                ('mime_type', models.CharField(blank=True, db_column='mime_type', max_length=100, null=True, verbose_name='文件MIME类型')),
                ('upload_status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], db_column='upload_status', default='completed', max_length=20, verbose_name='上传状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_column='upload_time', verbose_name='上传时间')),
                ('upload_ip', models.GenericIPAddressField(blank=True, db_column='upload_ip', null=True, verbose_name='上传IP地址')),
            ],
            options={
                'verbose_name': '学生作业文件',
                'verbose_name_plural': '学生作业文件',
                'db_table': 'student_homework_file',
            },
        ),
        migrations.RemoveIndex(
            model_name='teachingtoollog',
            name='teaching_to_teacher_606ca5_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachingtoollog',
            name='teaching_to_tool_na_d30acb_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachingtoollog',
            name='teaching_to_class_i_e460f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_class_i_c7140f_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentlearningprogress',
            name='student_lea_teacher_a5cb24_idx',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studenthomeworkfile',
            name='student_homework',
            field=models.ForeignKey(db_column='student_homework_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='teacher.studenthomework', verbose_name='作业提交'),
        ),
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='studentlearningprogress',
            name='teacher',
        ),
        migrations.AddIndex(
            model_name='studenthomeworkfile',
            index=models.Index(fields=['student_homework'], name='student_hom_student_0b87fc_idx'),
        ),
        migrations.AddIndex(
            model_name='studenthomeworkfile',
            index=models.Index(fields=['file_hash'], name='student_hom_file_ha_879d2b_idx'),
        ),
        migrations.DeleteModel(
            name='TeachingToolLog',
        ),
    ]
