# Generated by Django 4.2.7 on 2026-04-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_studenthomeworkfile_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teachingresource',
            name='teaching_re_chapter_2ecbfb_idx',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teachingres_teacher_9ad991_idx',
            old_name='teaching_re_teacher_971adc_idx',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teachingres_file_ha_e74814_idx',
            old_name='teacher_tea_file_ha_6531ff_idx',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teachingres_upload__b39c9b_idx',
            old_name='teacher_tea_upload__58d5a1_idx',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_desc',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_name',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_url',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='download_count',
            field=models.IntegerField(db_column='download_count', default=0, verbose_name='下载次数'),
        ),
        migrations.AlterModelTable(
            name='teachingresource',
            table='teachingresource',
        ),
    ]
