# Generated by Django 4.2.7 on 2026-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_studenthomeworkfile_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachingresource',
            table='teaching_resource',
        ),
    ]
