# Generated by Django 4.2.7 on 2026-03-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('content_check', '内容检查'), ('format_check', '格式检查'), ('policy_check', '政策检查')], max_length=20)),
                ('severity', models.IntegerField(default=1, help_text='0-低, 1-中, 2-高, 3-严重')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'review_rules',
            },
        ),
        migrations.CreateModel(
            name='ReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('review_fields', models.JSONField(default=list, help_text='审核领域')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_users',
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('new_submission', '新提交'), ('edit_review', '修改审核')], default='new_submission', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='0-普通, 1-优先, 2-紧急, 3-特急')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('submitter_id', models.IntegerField()),
                ('submitter_name', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_review_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='review.reviewuser')),
            ],
            options={
                'db_table': 'review_tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('task_create', '任务创建'), ('task_assign', '任务分配'), ('task_claim', '任务认领'), ('task_release', '任务释放'), ('ai_review', 'AI审核'), ('manual_review', '人工审核'), ('task_complete', '任务完成')], max_length=20)),
                ('action', models.TextField(help_text='操作内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='review.reviewtask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='review.reviewuser')),
            ],
            options={
                'db_table': 'review_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='审核意见', null=True)),
                ('issues', models.JSONField(default=list, help_text='发现的问题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.reviewuser')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_review', to='review.reviewtask')),
            ],
            options={
                'db_table': 'manual_reviews',
            },
        ),
        migrations.CreateModel(
            name='AIReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, help_text='AI综合评分')),
                ('issues', models.JSONField(default=list, help_text='发现的问题')),
                ('summary', models.TextField(blank=True, help_text='审核摘要', null=True)),
                ('conclusion', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '驳回')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_result', to='review.reviewtask')),
            ],
            options={
                'db_table': 'ai_review_results',
            },
        ),
    ]
