# Generated by Django 4.2.7 on 2026-03-10 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总体评分')),
                ('risk_level', models.CharField(blank=True, choices=[('low', '低风险'), ('medium', '中等风险'), ('high', '高风险'), ('critical', '严重风险')], max_length=20, null=True, verbose_name='风险等级')),
                ('content_compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='内容合规性评分')),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='准确性评分')),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完整性评分')),
                ('readability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='可读性评分')),
                ('detected_issues', models.JSONField(default=list, verbose_name='检测到的问题')),
                ('risk_items', models.JSONField(default=list, verbose_name='风险项')),
                ('suggestions', models.JSONField(default=list, verbose_name='AI建议')),
                ('raw_response', models.TextField(blank=True, verbose_name='AI原始响应')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='模型版本')),
                ('processing_time', models.IntegerField(blank=True, null=True, verbose_name='处理耗时(毫秒)')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='审核状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI审核记录',
                'verbose_name_plural': 'AI审核记录',
                'db_table': 'review_ai_record',
            },
        ),
        migrations.CreateModel(
            name='ManualReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('needs_revision', '需修改')], max_length=20, verbose_name='审核决定')),
                ('overall_comment', models.TextField(blank=True, verbose_name='总体审核意见')),
                ('content_quality_score', models.IntegerField(blank=True, null=True, verbose_name='内容质量评分')),
                ('accuracy_score', models.IntegerField(blank=True, null=True, verbose_name='准确性评分')),
                ('completeness_score', models.IntegerField(blank=True, null=True, verbose_name='完整性评分')),
                ('formatting_score', models.IntegerField(blank=True, null=True, verbose_name='格式规范评分')),
                ('language_score', models.IntegerField(blank=True, null=True, verbose_name='语言表达评分')),
                ('content_issues', models.JSONField(default=list, verbose_name='内容问题列表')),
                ('format_issues', models.JSONField(default=list, verbose_name='格式问题列表')),
                ('suggestions', models.TextField(blank=True, verbose_name='修改建议')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始审核时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成审核时间')),
                ('review_duration', models.IntegerField(blank=True, null=True, verbose_name='审核耗时(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
            ],
            options={
                'verbose_name': '人工审核记录',
                'verbose_name_plural': '人工审核记录',
                'db_table': 'review_manual_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('content', '内容规则'), ('format', '格式规则'), ('ai', 'AI规则')], max_length=20, verbose_name='规则类型')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('rule_config', models.JSONField(default=dict, verbose_name='规则配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核规则配置',
                'verbose_name_plural': '审核规则配置',
                'db_table': 'review_rule_config',
                'ordering': ['-priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '任务创建'), ('assigned', '任务分配'), ('claimed', '任务认领'), ('released', '任务释放'), ('ai_reviewed', 'AI审核完成'), ('manual_reviewed', '人工审核完成'), ('approved', '审核通过'), ('rejected', '审核驳回'), ('returned', '退回修改')], max_length=30, verbose_name='操作类型')),
                ('actor_type', models.CharField(choices=[('system', '系统'), ('reviewer', '审核员'), ('provider', '教材提供者')], default='system', max_length=20, verbose_name='操作人类型')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审核流程日志',
                'verbose_name_plural': '审核流程日志',
                'db_table': 'review_workflow_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='aireviewresult',
            name='task',
        ),
        migrations.RemoveField(
            model_name='manualreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='manualreview',
            name='task',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReviewRule',
        ),
        migrations.RemoveField(
            model_name='reviewuser',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='reviewtask',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': '审核任务', 'verbose_name_plural': '审核任务'},
        ),
        migrations.RemoveField(
            model_name='reviewtask',
            name='ai_review_id',
        ),
        migrations.RemoveField(
            model_name='reviewtask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='reviewtask',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='reviewtask',
            name='submitter_id',
        ),
        migrations.RemoveField(
            model_name='reviewtask',
            name='submitter_name',
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='chapter_count',
            field=models.IntegerField(default=0, verbose_name='章节数'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核截止时间'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='教材描述'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='提交人ID'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提交人名称'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='version_number',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派审核员'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='book_author',
            field=models.CharField(max_length=100, verbose_name='教材作者'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='book_id',
            field=models.IntegerField(verbose_name='教材ID'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='book_title',
            field=models.CharField(max_length=200, verbose_name='教材标题'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='priority',
            field=models.IntegerField(choices=[(0, '普通'), (1, '优先'), (2, '紧急'), (3, '特急')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('in_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='task_type',
            field=models.CharField(choices=[('new_submission', '新提交'), ('edit_review', '修改审核')], default='new_submission', max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='reviewtask',
            table='review_task',
        ),
        migrations.DeleteModel(
            name='AIReviewResult',
        ),
        migrations.DeleteModel(
            name='ManualReview',
        ),
        migrations.DeleteModel(
            name='ReviewLog',
        ),
        migrations.DeleteModel(
            name='ReviewUser',
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='review.reviewtask', verbose_name='审核任务'),
        ),
        migrations.AddField(
            model_name='manualreviewrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_records', to='review.reviewtask', verbose_name='审核任务'),
        ),
        migrations.AddField(
            model_name='aireviewrecord',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_record', to='review.reviewtask', verbose_name='审核任务'),
        ),
    ]
