# Generated by Django 4.2.7 on 2026-03-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_aireviewrecord_manualreviewrecord_reviewruleconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtask',
            name='book_isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='book_language',
            field=models.CharField(default='zh-CN', max_length=50, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='book_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='book_word_count',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分类名称'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='change_summary',
            field=models.TextField(blank=True, null=True, verbose_name='变更说明'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='modified_by_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='修改人部门'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='modified_by_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人工号'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='modified_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='修改人ID'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='modified_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='修改人姓名'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='修改人用户名'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='原始上传时间'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploader_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原始上传者部门'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploader_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='原始上传者工号'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploader_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='原始上传者ID'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploader_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原始上传者姓名'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='original_uploader_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='原始上传者用户名'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='previous_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上一版本号'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提交人部门'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='提交人邮箱'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='提交人工号'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提交人电话'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='提交人用户名'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签列表'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提交人姓名'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('department', models.CharField(max_length=100, verbose_name='所属部门')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('office_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='办公地点')),
                ('teaching_subjects', models.JSONField(default=list, verbose_name='教授科目')),
                ('research_areas', models.JSONField(default=list, verbose_name='研究领域')),
                ('total_uploaded_books', models.IntegerField(default=0, verbose_name='上传教材总数')),
                ('total_modified_books', models.IntegerField(default=0, verbose_name='修改教材总数')),
                ('approved_books', models.IntegerField(default=0, verbose_name='已通过教材数')),
                ('rejected_books', models.IntegerField(default=0, verbose_name='被驳回教材数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '教师档案',
                'verbose_name_plural': '教师档案',
                'db_table': 'review_teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='BookEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(verbose_name='教材ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='教材标题')),
                ('action', models.CharField(choices=[('created', '创建'), ('updated', '更新'), ('submitted', '提交审核'), ('approved', '审核通过'), ('rejected', '审核驳回'), ('published', '发布'), ('archived', '归档')], max_length=20, verbose_name='操作类型')),
                ('action_display', models.CharField(blank=True, max_length=100, verbose_name='操作描述')),
                ('actor_id', models.IntegerField(verbose_name='操作人ID')),
                ('actor_name', models.CharField(max_length=100, verbose_name='操作人姓名')),
                ('actor_username', models.CharField(max_length=150, verbose_name='操作人用户名')),
                ('actor_employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人工号')),
                ('actor_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人部门')),
                ('actor_role', models.CharField(max_length=20, verbose_name='操作人角色')),
                ('version_number', models.CharField(max_length=20, verbose_name='版本号')),
                ('previous_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='上一版本号')),
                ('changes_summary', models.TextField(blank=True, verbose_name='变更摘要')),
                ('changes_detail', models.JSONField(default=dict, verbose_name='变更详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='review.reviewtask', verbose_name='审核任务')),
            ],
            options={
                'verbose_name': '教材修改历史',
                'verbose_name_plural': '教材修改历史',
                'db_table': 'review_book_edit_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book_id', '-created_at'], name='review_book_book_id_b69f8e_idx'), models.Index(fields=['task_id', '-created_at'], name='review_book_task_id_347d13_idx'), models.Index(fields=['actor_id', '-created_at'], name='review_book_actor_i_ab8ef0_idx')],
            },
        ),
    ]
