# Generated by Django 4.2.7 on 2026-01-05 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='工具名称')),
                ('description', models.TextField(verbose_name='工具描述')),
                ('icon', models.CharField(default='🔧', max_length=20, verbose_name='工具图标')),
                ('book_id', models.IntegerField(blank=True, null=True, verbose_name='关联教材ID')),
                ('book_title', models.CharField(blank=True, max_length=100, verbose_name='关联教材名称')),
                ('chapter_number', models.IntegerField(blank=True, null=True, verbose_name='关联章节号')),
                ('first_section_id', models.IntegerField(blank=True, null=True, verbose_name='首个相关章节ID')),
                ('implementation_class', models.CharField(max_length=100, verbose_name='实现类名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名')),
                ('label', models.CharField(max_length=100, verbose_name='参数标签')),
                ('type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('select', '下拉选择'), ('textarea', '多行文本'), ('file', '文件上传')], max_length=20, verbose_name='参数类型')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='占位提示')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='默认值')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项列表')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='toolkit.tool', verbose_name='所属工具')),
            ],
            options={
                'verbose_name': '工具参数',
                'verbose_name_plural': '工具参数',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='toolkit.toolcategory', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(verbose_name='执行参数')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '运行中')], max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='toolkit.tool', verbose_name='执行工具')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '执行历史',
                'verbose_name_plural': '执行历史',
            },
        ),
    ]
