# Generated by Django 4.2.7 on 2025-10-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('description', models.TextField(verbose_name='描述')),
                ('tags', models.TextField(blank=True, default='[]', verbose_name='标签')),
                ('chapter_count', models.IntegerField(default=0, verbose_name='章节数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('type', models.CharField(choices=[('reading', '阅读'), ('video', '视频'), ('practice', '练习')], default='reading', max_length=20, verbose_name='章节类型')),
                ('duration', models.IntegerField(default=30, verbose_name='预计时长(分钟)')),
                ('description', models.TextField(verbose_name='章节描述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='章节内容')),
                ('code', models.TextField(blank=True, null=True, verbose_name='示例代码')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='编程语言')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题描述')),
                ('code_template', models.TextField(blank=True, null=True, verbose_name='代码模板')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='books.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '练习题',
                'verbose_name_plural': '练习题',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(verbose_name='输入数据')),
                ('expected_output', models.JSONField(verbose_name='期望输出')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='books.practice', verbose_name='所属练习')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
