# Generated by Django 4.2.7 on 2025-11-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('jupyter', 'Jupyter')], default='markdown', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='jupyter_content',
            field=models.TextField(blank=True, null=True, verbose_name='Jupyter文档内容'),
        ),
    ]
