# Generated by Django 4.2.7 on 2025-11-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_chapter_content_type_chapter_jupyter_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterCell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_type', models.CharField(choices=[('code', '代码'), ('markdown', 'Markdown'), ('raw', '原始')], default='code', max_length=20, verbose_name='单元格类型')),
                ('source', models.TextField(blank=True, default='', verbose_name='源代码')),
                ('execution_count', models.IntegerField(blank=True, null=True, verbose_name='执行计数')),
                ('metadata', models.JSONField(default=dict, verbose_name='单元格元数据')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Jupyter单元格',
                'verbose_name_plural': 'Jupyter单元格',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JupyterOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_type', models.CharField(choices=[('stream', '流'), ('display_data', '显示数据'), ('execute_result', '执行结果'), ('error', '错误'), ('clear_output', '清除输出')], max_length=20, verbose_name='输出类型')),
                ('data', models.JSONField(default=dict, verbose_name='输出数据')),
                ('ename', models.CharField(blank=True, max_length=100, null=True, verbose_name='错误名称')),
                ('evalue', models.TextField(blank=True, null=True, verbose_name='错误值')),
                ('traceback', models.JSONField(blank=True, null=True, verbose_name='错误栈')),
                ('execution_count', models.IntegerField(blank=True, null=True, verbose_name='执行计数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='books.jupytercell', verbose_name='所属单元格')),
            ],
            options={
                'verbose_name': 'Jupyter输出',
                'verbose_name_plural': 'Jupyter输出',
            },
        ),
        migrations.CreateModel(
            name='JupyterNotebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbformat', models.IntegerField(default=4, verbose_name='Jupyter格式版本')),
                ('nbformat_minor', models.IntegerField(default=5, verbose_name='Jupyter格式次版本')),
                ('metadata', models.JSONField(default=dict, help_text='存储kernelspec、language_info等Jupyter标准元数据', verbose_name='Jupyter元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_notebook', to='books.chapter', verbose_name='关联章节')),
            ],
            options={
                'verbose_name': 'Jupyter笔记本',
                'verbose_name_plural': 'Jupyter笔记本',
            },
        ),
        migrations.AddField(
            model_name='jupytercell',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='books.jupyternotebook', verbose_name='所属Notebook'),
        ),
    ]
