# Generated by Django 4.2.7 on 2025-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_jupyter_notebook_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='merged_content',
            field=models.TextField(blank=True, null=True, verbose_name='合并内容'),
        ),
    ]
