# Generated by Django 4.2.7 on 2025-11-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_chapter_merged_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.IntegerField(default=0, verbose_name='章节层级'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='父章节排序'),
        ),
    ]
