# Generated by Django 4.2.7 on 2025-11-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_chapter_level_chapter_parent_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='parent_order',
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_main_chapter',
            field=models.BooleanField(default=True, verbose_name='是否为主章节'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_chapters', to='books.chapter', verbose_name='父章节'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='level',
            field=models.IntegerField(default=1, verbose_name='章节级别'),
        ),
    ]
