# Generated by Django 4.2.7 on 2026-01-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_chapter_parent_order_chapter_is_main_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='question_type',
            field=models.CharField(
                choices=[('choice', '选择题'), ('fill', '填空题'), ('code_completion', '代码补全题'), ('programming', '编程题')],
                default='programming',
                max_length=20,
                verbose_name='题目类型'
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='practice',
            name='title',
            field=models.CharField(default='练习题', max_length=255, verbose_name='题目名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='题目描述'),
        ),
        migrations.AddField(
            model_name='practice',
            name='language',
            field=models.CharField(default='python', max_length=50, verbose_name='编程语言'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='practice',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='practice',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='practice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='practice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.IntegerField(default=0, verbose_name='测试用例顺序'),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='PracticeChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
                ('order', models.IntegerField(default=0, verbose_name='选项顺序')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_options', to='books.practice', verbose_name='所属练习题')),
            ],
            options={
                'verbose_name': '选择题选项',
                'verbose_name_plural': '选择题选项',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeFillBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='提示文本')),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True, verbose_name='占位符')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='正确答案')),
                ('order', models.IntegerField(default=0, verbose_name='空位顺序')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blanks', to='books.practice', verbose_name='所属练习题')),
            ],
            options={
                'verbose_name': '填空题空位',
                'verbose_name_plural': '填空题空位',
                'ordering': ['order'],
            },
        ),
    ]
