# Generated by Django 4.2.7 on 2026-01-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_add_sample_practice_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['order'], 'verbose_name': '练习题', 'verbose_name_plural': '练习题'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AlterField(
            model_name='practice',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='books.chapter', verbose_name='所属章节'),
        ),
    ]
