# Generated by Django 4.2.7 on 2026-01-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_practice_options_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='code_template',
        ),
        migrations.AddField(
            model_name='practice',
            name='questions',
            field=models.JSONField(default=list, help_text='存储多个问题的JSON数组', verbose_name='问题列表'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='练习题集名称'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='练习题集描述'),
        ),
    ]
