# Generated by Django 5.2 on 2026-01-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_modify_practice_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '书籍标签',
                'verbose_name_plural': '书籍标签',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='是否归档'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.TextField(blank=True, default='[]', verbose_name='标签(JSON)'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.bookcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.bookcategory', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '驳回')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='教材')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '教材审核记录',
                'verbose_name_plural': '教材审核记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tag_objects',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.booktag', verbose_name='标签对象'),
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('description', models.TextField(verbose_name='描述')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_versions/', verbose_name='版本PDF文件')),
                ('tags', models.TextField(blank=True, default='[]', verbose_name='标签(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='版本说明')),
                ('is_branch', models.BooleanField(default=False, verbose_name='是否分支版本')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.book', verbose_name='原始书籍')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='版本创建人')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='books.bookversion', verbose_name='父版本')),
            ],
            options={
                'verbose_name': '教材版本',
                'verbose_name_plural': '教材版本',
                'ordering': ['book_id', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ChapterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', '视频'), ('image', '图片'), ('audio', '音频'), ('attachment', '附件')], max_length=20, verbose_name='资源类型')),
                ('url', models.URLField(blank=True, null=True, verbose_name='资源URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='chapter_media/%Y/%m/', verbose_name='资源文件')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='books.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '章节多媒体资源',
                'verbose_name_plural': '章节多媒体资源',
                'ordering': ['chapter_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='章节内容')),
                ('code', models.TextField(blank=True, null=True, verbose_name='示例代码')),
                ('jupyter_content', models.TextField(blank=True, null=True, verbose_name='Jupyter文档内容')),
                ('merged_content', models.TextField(blank=True, null=True, verbose_name='合并内容')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='编程语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='版本说明')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.chapter', verbose_name='原始章节')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='版本创建人')),
            ],
            options={
                'verbose_name': '章节版本',
                'verbose_name_plural': '章节版本',
                'ordering': ['chapter_id', '-version_number'],
            },
        ),
    ]
