# Generated by Django 4.2.7 on 2026-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_booktag_book_is_archived_alter_book_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='当前版本'),
        ),
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='详细介绍'),
        ),
    ]
