# Generated by Django 4.2.7 on 2026-01-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_current_version_book_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='introduction',
        ),
    ]
