# Generated by Django 5.2 on 2026-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='当前版本'),
        ),
    ]
