# Generated by Django 5.2 on 2026-01-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='bookversion',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题'),
        ),
    ]
