# Generated by Django 6.0.4 on 2026-04-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_subtitle_bookversion_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='book_docx/', verbose_name='DOCX文件'),
        ),
        migrations.AddField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='book_epub/', verbose_name='EPUB文件'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='zh-CN', max_length=50, null=True, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='book',
            name='md_file',
            field=models.FileField(blank=True, null=True, upload_to='book_md/', verbose_name='Markdown文件'),
        ),
        migrations.AddField(
            model_name='book',
            name='old_tags',
            field=models.TextField(blank=True, default='[]', verbose_name='旧版标签'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出版日期'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('pending_review', '待审核'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='书籍状态'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_chapters',
            field=models.IntegerField(default=0, verbose_name='总章节数'),
        ),
        migrations.AddField(
            model_name='book',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
        migrations.CreateModel(
            name='AILearningGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindmap', models.TextField(blank=True, null=True, verbose_name='思维导图')),
                ('ppt', models.TextField(blank=True, null=True, verbose_name='PPT')),
                ('key_concepts', models.JSONField(blank=True, null=True, verbose_name='关键概念对比')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='豆包重点笔记')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='生成状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_learning_guides', to='books.book', verbose_name='所属书籍')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_learning_guides', to='books.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': 'AI 导学内容',
                'verbose_name_plural': 'AI 导学内容',
                'unique_together': {('book', 'chapter')},
            },
        ),
    ]
