# Generated by Django 4.2.7 on 2026-04-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_docx_file_book_epub_file_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailearningguide',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='章节总结'),
        ),
    ]
