# Generated by Django 4.2.7 on 2026-04-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0020_ailearningguide_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已同意'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='申请原因')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='books.book', verbose_name='申请书籍')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '权限申请',
                'verbose_name_plural': '权限申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '已开放'), ('locked', '已加锁'), ('requested', '申请中')], default='open', max_length=20, verbose_name='权限状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='books.book', verbose_name='所属书籍')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '书籍权限',
                'verbose_name_plural': '书籍权限',
                'unique_together': {('book', 'user')},
            },
        ),
    ]
