# Generated by Django 4.2.7 on 2025-10-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('minutes', models.IntegerField(default=0, verbose_name='学习时长(分钟)')),
            ],
            options={
                'verbose_name': '学习热力图数据',
                'verbose_name_plural': '学习热力图数据',
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0, verbose_name='学习进度(%)')),
                ('last_learn_time', models.DateTimeField(auto_now=True, verbose_name='最后学习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('user_code', models.TextField(blank=True, null=True, verbose_name='用户提交的代码')),
                ('completed_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to='books.book', verbose_name='教材')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to='books.chapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
            },
        ),
    ]
