# Generated by Django 4.2.7 on 2025-10-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='题目')),
                ('difficulty', models.IntegerField(default=2, verbose_name='难度(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='books.book', verbose_name='教材')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='books.chapter', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'ordering': ['-created_at'],
            },
        ),
    ]
