# Generated by Django 4.2.7 on 2025-11-01 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_book_owner'),
        ('learning', '0003_wrongquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.IntegerField(verbose_name='阶段顺序')),
                ('title', models.CharField(max_length=200, verbose_name='阶段标题')),
                ('description', models.TextField(verbose_name='阶段描述')),
                ('learning_goals', models.JSONField(default=list, verbose_name='学习目标列表')),
                ('required_skills', models.JSONField(default=list, verbose_name='前置技能要求')),
                ('estimated_duration', models.IntegerField(verbose_name='预计学习时长(小时)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路线图阶段',
                'verbose_name_plural': '路线图阶段',
                'ordering': ['roadmap', 'stage_order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(choices=[('business', '经管类'), ('humanities', '文史类'), ('arts', '艺术类'), ('science', '理工科')], max_length=50, verbose_name='专业类别')),
                ('title', models.CharField(max_length=200, verbose_name='路线图标题')),
                ('description', models.TextField(verbose_name='路线图描述')),
                ('difficulty_level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '高级')], max_length=20, verbose_name='难度级别')),
                ('estimated_hours', models.IntegerField(default=40, verbose_name='预计学习时长(小时)')),
                ('tags', models.JSONField(default=list, verbose_name='技能标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路线图模板',
                'verbose_name_plural': '路线图模板',
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='总体进度百分比')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始学习时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('custom_goals', models.JSONField(default=list, verbose_name='用户自定义目标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user_paths', to='learning.roadmapstage', verbose_name='当前阶段')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='learning.roadmaptemplate', verbose_name='路线图模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户学习路径',
                'verbose_name_plural': '用户学习路径',
                'unique_together': {('user', 'roadmap')},
            },
        ),
        migrations.AddField(
            model_name='roadmapstage',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='learning.roadmaptemplate', verbose_name='所属路线图'),
        ),
        migrations.CreateModel(
            name='RoadmapBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_order', models.IntegerField(default=0, verbose_name='推荐阅读顺序')),
                ('importance', models.IntegerField(choices=[(1, '了解'), (2, '熟悉'), (3, '重点'), (4, '核心')], default=3, verbose_name='重要程度')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='学习建议')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_books', to='books.book', verbose_name='教材')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_books', to='learning.roadmapstage', verbose_name='所属阶段')),
            ],
            options={
                'verbose_name': '路线图书籍',
                'verbose_name_plural': '路线图书籍',
                'ordering': ['stage', 'recommended_order'],
            },
        ),
        migrations.CreateModel(
            name='UserPathStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='阶段进度百分比')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='学习笔记')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.roadmapstage', verbose_name='路线图阶段')),
                ('user_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='learning.userlearningpath', verbose_name='用户学习路径')),
            ],
            options={
                'verbose_name': '用户路径阶段',
                'verbose_name_plural': '用户路径阶段',
                'unique_together': {('user_path', 'stage')},
            },
        ),
    ]
