# Generated by Django 4.2.7 on 2025-11-02 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0006_note_is_starred_notetag_notecategory_note_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('question', models.TextField(verbose_name='问题内容')),
                ('code_template', models.TextField(blank=True, null=True, verbose_name='代码模板')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='编程语言')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度')),
                ('category', models.CharField(choices=[('python_basic', 'Python基础'), ('javascript_basic', 'JavaScript基础'), ('algorithm', '算法基础'), ('logic', '编程思维')], max_length=50, verbose_name='题目分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '练习题',
                'verbose_name_plural': '练习题',
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.TextField(blank=True, null=True, verbose_name='用户提交的代码')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='learning.exercise', verbose_name='练习题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习题记录',
                'verbose_name_plural': '练习题记录',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.JSONField(verbose_name='输入数据')),
                ('expected_output', models.JSONField(verbose_name='期望输出')),
                ('order', models.IntegerField(default=0, verbose_name='测试用例顺序')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learning.exercise', verbose_name='练习题')),
            ],
            options={
                'verbose_name': '练习题测试用例',
                'verbose_name_plural': '练习题测试用例',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NoteCategory',
        ),
        migrations.DeleteModel(
            name='NoteTag',
        ),
    ]
