# Generated by Django 4.2.7 on 2025-11-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_owner'),
        ('learning', '0007_exercise_exerciserecord_exercisetestcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='attempt_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后尝试时间'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='learning.exercise', verbose_name='练习题'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='books.book', verbose_name='教材'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='books.chapter', verbose_name='章节'),
        ),
    ]
