# Generated by Django 4.2.7 on 2025-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_wrongquestion_attempt_time_wrongquestion_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='question_type',
            field=models.CharField(default='unknown', max_length=20, verbose_name='题目类型'),
        ),
    ]
