# Generated by Django 4.2.7 on 2025-11-06 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_chapter_content_type_chapter_jupyter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0009_wrongquestion_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('content', models.TextField(verbose_name='文档内容（Markdown格式）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jupyter_documents', to='books.book', verbose_name='关联书籍')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jupyter_documents', to='books.chapter', verbose_name='关联章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_documents', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Jupyter文档',
                'verbose_name_plural': 'Jupyter文档',
                'ordering': ['-updated_at'],
            },
        ),
    ]
