# Generated by Django 4.2.7 on 2025-11-10 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_chapter_parent_order_chapter_is_main_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0010_jupyterdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_score', models.FloatField(default=0.5, verbose_name='视觉学习偏好度')),
                ('auditory_score', models.FloatField(default=0.5, verbose_name='听觉学习偏好度')),
                ('reading_score', models.FloatField(default=0.5, verbose_name='读写学习偏好度')),
                ('kinesthetic_score', models.FloatField(default=0.5, verbose_name='动手实践偏好度')),
                ('pace_preference', models.CharField(choices=[('fast', '快速学习'), ('deep', '深入学习'), ('balanced', '平衡型')], default='balanced', max_length=20, verbose_name='学习节奏偏好')),
                ('environment_preference', models.CharField(choices=[('quiet', '安静环境'), ('moderate_noise', '适度噪音'), ('collaborative', '协作环境')], default='quiet', max_length=50, verbose_name='学习环境偏好')),
                ('preferred_resource_types', models.JSONField(default=list, verbose_name='偏好的学习资源类型')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习风格',
                'verbose_name_plural': '学习风格',
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('roadmap', '路线图'), ('stage', '学习阶段'), ('book', '书籍'), ('chapter', '章节'), ('exercise', '练习题'), ('resource', '其他资源')], max_length=50, verbose_name='推荐类型')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='推荐原因')),
                ('score', models.FloatField(default=0.0, verbose_name='推荐分数')),
                ('recommended_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('user_feedback', models.CharField(choices=[('none', '未反馈'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='none', max_length=20, verbose_name='用户反馈')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='反馈时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='books.book', verbose_name='推荐书籍')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='books.chapter', verbose_name='推荐章节')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning.exercise', verbose_name='推荐练习题')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning.roadmaptemplate', verbose_name='推荐路线图')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning.roadmapstage', verbose_name='推荐阶段')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('user_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning.userlearningpath', verbose_name='用户学习路径')),
            ],
            options={
                'verbose_name': '学习推荐',
                'verbose_name_plural': '学习推荐',
                'ordering': ['-score', '-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goals', models.JSONField(default=list, verbose_name='学习目标')),
                ('interest_areas', models.JSONField(default=list, verbose_name='兴趣领域')),
                ('daily_available_minutes', models.IntegerField(default=60, verbose_name='每天可用学习时间')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='是否启用学习提醒')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='学习提醒时间')),
                ('difficulty_preference', models.CharField(choices=[('easy', '偏简单'), ('medium', '适中'), ('challenging', '偏难'), ('mixed', '混合')], default='medium', max_length=20, verbose_name='难度偏好')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习偏好',
                'verbose_name_plural': '学习偏好',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_point', models.CharField(max_length=255, verbose_name='知识点名称')),
                ('mastery_level', models.FloatField(default=0.0, verbose_name='掌握度评分')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='最近评估时间')),
                ('assessment_count', models.IntegerField(default=0, verbose_name='评估次数')),
                ('tags', models.JSONField(default=list, verbose_name='知识点标签')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_mastery', to='books.book', verbose_name='关联书籍')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_mastery', to='books.chapter', verbose_name='关联章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_mastery', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '知识掌握度',
                'verbose_name_plural': '知识掌握度',
                'unique_together': {('user', 'knowledge_point', 'book', 'chapter')},
            },
        ),
    ]
