# Generated by Django 4.2.7 on 2026-01-04 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_chapter_parent_order_chapter_is_main_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0011_learningstyle_learningrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='note_attachments/%Y/%m/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小（字节）')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '笔记附件',
                'verbose_name_plural': '笔记附件',
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share_code', models.CharField(max_length=32, unique=True, verbose_name='分享码')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '笔记分享',
                'verbose_name_plural': '笔记分享',
            },
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#409EFF', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '笔记标签',
                'verbose_name_plural': '笔记标签',
            },
        ),
        migrations.CreateModel(
            name='NoteTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '笔记标签关联',
                'verbose_name_plural': '笔记标签关联',
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '笔记版本历史',
                'verbose_name_plural': '笔记版本历史',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='books.book', verbose_name='关联教材'),
        ),
        migrations.AddField(
            model_name='note',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='books.chapter', verbose_name='关联章节'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间'),
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='位置信息（JSON格式）'),
        ),
        migrations.AddField(
            model_name='note',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='learning_no_user_id_2d0f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['book', 'chapter'], name='learning_no_book_id_5a411d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_favorite'], name='learning_no_is_favo_a18781_idx'),
        ),
        migrations.AddField(
            model_name='noteversion',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='learning.note', verbose_name='笔记'),
        ),
        migrations.AddField(
            model_name='notetagrelation',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='learning.note'),
        ),
        migrations.AddField(
            model_name='notetagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_relations', to='learning.notetag'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='learning.note', verbose_name='笔记'),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to=settings.AUTH_USER_MODEL, verbose_name='分享者'),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='shared_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='learning.note', verbose_name='笔记'),
        ),
        migrations.AlterUniqueTogether(
            name='notetagrelation',
            unique_together={('note', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together={('user', 'name')},
        ),
    ]
