# Generated by Django 4.2.7 on 2026-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_noteattachment_noteshare_notetag_notetagrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='标签名称'),
        ),
    ]
