# Generated by Django 4.2.7 on 2026-01-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_notetag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='图谱名称')),
                ('description', models.TextField(verbose_name='图谱描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '知识图谱',
                'verbose_name_plural': '知识图谱',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='节点标题')),
                ('type', models.CharField(choices=[('concept', '概念层'), ('application', '应用层'), ('skill', '技能层'), ('resource', '资源层')], max_length=50, verbose_name='节点类型')),
                ('level', models.IntegerField(default=1, verbose_name='节点层级')),
                ('difficulty', models.FloatField(default=3.0, verbose_name='难度系数')),
                ('importance', models.FloatField(default=3.0, verbose_name='重要程度')),
                ('description', models.TextField(verbose_name='节点描述')),
                ('professional_group', models.CharField(choices=[('business', '经管类'), ('humanities', '文史类'), ('arts', '艺术类'), ('science', '理工科')], max_length=50, verbose_name='专业组')),
                ('tags', models.JSONField(default=list, verbose_name='节点标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning.knowledgegraph', verbose_name='所属图谱')),
            ],
            options={
                'verbose_name': '知识节点',
                'verbose_name_plural': '知识节点',
                'ordering': ['level', 'importance', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='LLMIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('baidu', '百度文心一言'), ('alibaba', '阿里云通义千问')], max_length=50, verbose_name='大模型提供商')),
                ('api_key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template', models.TextField(verbose_name='模板内容')),
                ('type', models.CharField(choices=[('knowledge_extraction', '知识提取'), ('path_generation', '路径生成'), ('content_explanation', '内容解释'), ('feedback_generation', '反馈生成'), ('question_answering', '问答')], max_length=50, verbose_name='模板类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Prompt模板',
                'verbose_name_plural': 'Prompt模板',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('prerequisite', '前置依赖'), ('related', '相关知识'), ('application', '应用场景'), ('advanced', '进阶知识'), ('professional', '专业关联')], max_length=50, verbose_name='关系类型')),
                ('strength', models.FloatField(default=1.0, verbose_name='关系强度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='learning.knowledgegraph', verbose_name='所属图谱')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='learning.knowledgenode', verbose_name='源节点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='learning.knowledgenode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '知识关系',
                'verbose_name_plural': '知识关系',
                'unique_together': {('source', 'target', 'relation_type')},
            },
        ),
    ]
