# Generated by Django 4.2.7 on 2026-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_knowledgegraph_knowledgenode_llmintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgenode',
            name='type',
            field=models.CharField(choices=[('concept', '概念层'), ('professional_integration', '专业融合层'), ('skill', '技能层'), ('resource', '资源层')], max_length=50, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='llmintegration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('baidu', '百度文心一言'), ('alibaba', '阿里云通义千问'), ('doubao', '豆包(Doubao)')], max_length=50, verbose_name='大模型提供商'),
        ),
    ]
