# Generated by Django 4.2.7 on 2026-01-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0015_alter_knowledgenode_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('interaction_type', models.CharField(choices=[('question', '提问'), ('code_completion', '代码补全'), ('explanation', '解释说明'), ('other', '其他')], db_index=True, default='question', max_length=50, verbose_name='交互类型')),
                ('user_input', models.TextField(verbose_name='用户输入内容')),
                ('ai_response', models.TextField(verbose_name='AI回复内容')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='用于关联同一会话的多次交互', max_length=100, null=True, verbose_name='会话ID')),
                ('context', models.JSONField(blank=True, default=dict, help_text='存储额外的上下文信息，如代码语言、章节信息等', null=True, verbose_name='上下文信息')),
                ('response_time', models.FloatField(blank=True, help_text='AI响应耗时', null=True, verbose_name='响应时间(秒)')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='使用的Token数量')),
                ('is_satisfied', models.BooleanField(blank=True, default=None, help_text='用户对回复的满意度评价', null=True, verbose_name='用户满意度')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI交互记录',
                'verbose_name_plural': 'AI交互记录',
                'db_table': 'ai_interaction_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_interact_user_id_aa69f5_idx'), models.Index(fields=['user', 'session_id'], name='ai_interact_user_id_63669e_idx'), models.Index(fields=['user', 'interaction_type', '-created_at'], name='ai_interact_user_id_b2458c_idx')],
            },
        ),
    ]
