# Generated by Django 4.2.7 on 2026-03-10 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0018_book_subtitle_bookversion_subtitle'),
        ('learning', '0016_aiinteractionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyKnowledgeNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='节点标题')),
                ('description', models.TextField(verbose_name='节点描述')),
                ('level', models.IntegerField(choices=[(0, 'Level 0 - 概念层'), (1, 'Level 1 - 分类层'), (2, 'Level 2 - 实体层'), (3, 'Level 3 - 动态层')], db_index=True, verbose_name='知识层级')),
                ('node_type', models.CharField(choices=[('concept', '概念'), ('skill', '技能'), ('resource', '资源'), ('path', '路径'), ('application', '应用')], max_length=50, verbose_name='节点类型')),
                ('temporal', models.CharField(choices=[('atemporal', '无时间性'), ('long_term', '长期趋势'), ('historical', '历史时态'), ('realtime', '实时流')], default='atemporal', max_length=20, verbose_name='时间属性')),
                ('difficulty', models.FloatField(default=1.0, verbose_name='难度系数')),
                ('importance', models.FloatField(default=3.0, verbose_name='重要性')),
                ('tags', models.JSONField(default=list, verbose_name='标签列表')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('professional_group', models.CharField(db_index=True, max_length=50, verbose_name='专业组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'StrategyKG知识节点',
                'verbose_name_plural': 'StrategyKG知识节点',
            },
        ),
        migrations.CreateModel(
            name='StrategyLearningPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='路径标题')),
                ('description', models.TextField(verbose_name='路径描述')),
                ('professional_group', models.CharField(max_length=50, verbose_name='专业组')),
                ('difficulty_level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '高级')], max_length=20, verbose_name='难度级别')),
                ('estimated_hours', models.IntegerField(default=40, verbose_name='预计学习时长(小时)')),
                ('tags', models.JSONField(default=list, verbose_name='技能标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'StrategyKG学习路径',
                'verbose_name_plural': 'StrategyKG学习路径',
            },
        ),
        migrations.CreateModel(
            name='StrategyPathNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='节点顺序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必修')),
                ('estimated_hours', models.IntegerField(default=0, verbose_name='预计学习时长(小时)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_associations', to='learning.strategyknowledgenode', verbose_name='知识节点')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_nodes', to='learning.strategylearningpath', verbose_name='所属路径')),
            ],
            options={
                'verbose_name': 'StrategyKG路径节点',
                'verbose_name_plural': 'StrategyKG路径节点',
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserStrategyPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0, verbose_name='总体进度百分比')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('active', '学习中'), ('paused', '暂停'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='状态')),
                ('custom_goals', models.JSONField(default=list, verbose_name='用户自定义目标')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='学习笔记')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='learning.strategypathnode', verbose_name='当前节点')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='learning.strategylearningpath', verbose_name='学习路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_paths', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户StrategyKG路径',
                'verbose_name_plural': '用户StrategyKG路径',
            },
        ),
        migrations.CreateModel(
            name='UserNodeProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mastery_level', models.IntegerField(choices=[(0, '未学习'), (1, '了解'), (2, '熟悉'), (3, '掌握'), (4, '精通')], default=0, verbose_name='掌握程度')),
                ('learning_hours', models.FloatField(default=0, verbose_name='学习时长(小时)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='学习笔记')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.strategyknowledgenode', verbose_name='知识节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('user_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progresses', to='learning.userstrategypath', verbose_name='用户路径')),
            ],
            options={
                'verbose_name': '用户节点进度',
                'verbose_name_plural': '用户节点进度',
            },
        ),
        migrations.CreateModel(
            name='StrategyUserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('professional_group', models.CharField(max_length=50, verbose_name='专业组')),
                ('knowledge_level', models.CharField(choices=[('beginner', '初学者'), ('intermediate', '中级'), ('advanced', '高级')], max_length=20, verbose_name='知识水平')),
                ('learning_style', models.CharField(choices=[('visual', '视觉学习者'), ('auditory', '听觉学习者'), ('reading', '读写学习者'), ('kinesthetic', '动手实践学习者')], max_length=20, verbose_name='学习风格')),
                ('pacing_preference', models.CharField(choices=[('fast', '快速学习'), ('deep', '深入学习'), ('balanced', '平衡型')], default='balanced', max_length=20, verbose_name='学习节奏偏好')),
                ('interests', models.JSONField(default=list, verbose_name='兴趣领域')),
                ('learning_goals', models.JSONField(default=list, verbose_name='学习目标')),
                ('total_learning_minutes', models.IntegerField(default=0, verbose_name='总学习时长(分钟)')),
                ('completed_practices', models.IntegerField(default=0, verbose_name='完成练习数')),
                ('avg_practice_score', models.FloatField(default=0, verbose_name='平均练习得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'StrategyKG用户画像',
                'verbose_name_plural': 'StrategyKG用户画像',
            },
        ),
        migrations.CreateModel(
            name='StrategyResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='资源标题')),
                ('description', models.TextField(verbose_name='资源描述')),
                ('resource_type', models.CharField(choices=[('book', '教材'), ('video', '视频'), ('article', '文章'), ('practice', '练习'), ('project', '项目')], max_length=20, verbose_name='资源类型')),
                ('url', models.URLField(blank=True, null=True, verbose_name='资源链接')),
                ('difficulty', models.FloatField(default=1.0, verbose_name='难度')),
                ('quality_score', models.FloatField(default=3.0, verbose_name='质量评分')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_resources', to='books.book', verbose_name='关联教材')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_resources', to='books.chapter', verbose_name='关联章节')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.strategyknowledgenode', verbose_name='关联知识点')),
            ],
            options={
                'verbose_name': 'StrategyKG学习资源',
                'verbose_name_plural': 'StrategyKG学习资源',
            },
        ),
        migrations.CreateModel(
            name='StrategyRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('requires', '前置依赖'), ('belongs_to', '属于'), ('includes', '包含'), ('recommends', '推荐'), ('leads_to', '导向'), ('applies_to', '应用于'), ('similar_to', '相似于')], max_length=50, verbose_name='关系类型')),
                ('strength', models.FloatField(default=1.0, verbose_name='关系强度')),
                ('confidence', models.FloatField(default=1.0, verbose_name='置信度')),
                ('metadata', models.JSONField(default=dict, verbose_name='关系元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='learning.strategyknowledgenode', verbose_name='源节点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='learning.strategyknowledgenode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': 'StrategyKG知识关系',
                'verbose_name_plural': 'StrategyKG知识关系',
            },
        ),
        migrations.CreateModel(
            name='StrategyRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('path', '学习路径'), ('node', '知识点'), ('resource', '学习资源'), ('practice', '练习题')], max_length=20, verbose_name='推荐类型')),
                ('matching_score', models.FloatField(default=0, verbose_name='匹配度分数')),
                ('recommendation_reason', models.TextField(verbose_name='推荐理由')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='是否接受')),
                ('user_feedback', models.TextField(blank=True, null=True, verbose_name='用户反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recommended_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.strategyknowledgenode', verbose_name='推荐节点')),
                ('recommended_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.strategylearningpath', verbose_name='推荐路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'StrategyKG推荐',
                'verbose_name_plural': 'StrategyKG推荐',
                'ordering': ['-matching_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyknowledgenode',
            index=models.Index(fields=['level', 'professional_group'], name='learning_st_level_5d3bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyknowledgenode',
            index=models.Index(fields=['node_type'], name='learning_st_node_ty_9b9b14_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyknowledgenode',
            index=models.Index(fields=['difficulty'], name='learning_st_difficu_b328a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstrategypath',
            unique_together={('user', 'path')},
        ),
        migrations.AlterUniqueTogether(
            name='usernodeprogress',
            unique_together={('user', 'node')},
        ),
        migrations.AddIndex(
            model_name='strategyrelation',
            index=models.Index(fields=['relation_type'], name='learning_st_relatio_95d560_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrelation',
            index=models.Index(fields=['strength'], name='learning_st_strengt_ab793d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyrelation',
            unique_together={('source', 'target', 'relation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='strategypathnode',
            unique_together={('path', 'node')},
        ),
    ]
