# Generated by Django 4.2.7 on 2026-01-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_line_numbers',
            field=models.BooleanField(default=True, verbose_name='显示代码行号'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='use_vim_mode',
            field=models.BooleanField(default=False, verbose_name='使用Vim模式'),
        ),
    ]
