# Generated by Django 4.2.7 on 2026-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences_show_line_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_records_visibility',
            field=models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('private', '私密')], default='private', max_length=20, verbose_name='学习记录可见性'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('private', '私密')], default='public', max_length=20, verbose_name='资料可见性'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='daily_reminder',
            field=models.BooleanField(default=True, verbose_name='每日学习提醒'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='deadline_reminder',
            field=models.BooleanField(default=True, verbose_name='截止日期提醒'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='enable_learning_reminders',
            field=models.BooleanField(default=True, verbose_name='启用学习提醒'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='interests',
            field=models.JSONField(default=list, verbose_name='兴趣领域'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='learning_goals',
            field=models.JSONField(default=list, verbose_name='学习目标'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='learning_stage',
            field=models.CharField(choices=[('beginner', '初学者'), ('intermediate', '进阶者'), ('advanced', '高级学习者')], default='beginner', max_length=20, verbose_name='学习阶段'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业方向'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reminder_time',
            field=models.TimeField(default='09:00', verbose_name='提醒时间'),
        ),
    ]
