# Generated by Django 4.2.7 on 2026-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio_user_learning_records_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='major_category',
            field=models.CharField(blank=True, choices=[('business', '经管类'), ('humanities', '文史类'), ('arts', '艺术类'), ('science', '理工科')], max_length=50, null=True, verbose_name='专业类别'),
        ),
    ]
