# Generated by Django 4.2.7 on 2026-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreferences_major_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('provider', '教材提供者'), ('reviewer', '审核员'), ('admin', '管理员')], default='student', max_length=20, verbose_name='用户角色'),
        ),
    ]
